In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
df=pd.read_csv(r'C:\Users\DELL\Downloads\homeprices.csv')

In [19]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [20]:
X=df.drop('price',axis=1)

In [21]:
X

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [22]:
y=df['price']

In [23]:
y

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [24]:
lr=LinearRegression()

In [25]:
lr.fit(X,y)

LinearRegression()

In [26]:
lr.score(X,y)

0.9584301138199486

In [27]:
lr.coef_

array([135.78767123])

In [28]:
lr.intercept_

180616.43835616432

In [29]:
lr.predict([[5000]])

array([859554.79452055])

# Save Method for model by price

In [30]:
import pickle

# Save

In [31]:
with open('modellr','wb') as f:  #wb=write binary  save model by using pickle
    pickle.dump(lr,f)

# Load

In [32]:
with open('modellr','rb') as f:
    mp=pickle.load(f)
    

In [33]:
mp

LinearRegression()

In [34]:
mp.coef_

array([135.78767123])

In [35]:
mp.predict([[5000]])

array([859554.79452055])

# save model using job lib

In [36]:
import joblib

# Save the file

In [37]:
joblib.dump(lr,'modellrjb')

['modellrjb']

# Load

In [38]:
jb=joblib.load('modellrjb')

In [39]:
jb.predict([[5000]])

array([859554.79452055])

In [40]:
#deploy the model

In [41]:
import pickle


In [42]:
with open('modellr','rb') as f:
    mp=pickle.load(f)
    

In [43]:
mp

LinearRegression()

In [44]:
mp.predict([[2000]])

array([452191.78082192])

In [45]:
from tkinter import*

In [61]:
win=Tk()
win.title('MyApp')
win.configure(bg='yellow')
win.geometry('600x300')
def fun():
    value=var.get()
    with open('modellr','rb') as f:
        mp=pickle.load(f)
    a=mp.predict([[value]])
    lbl1.config(text='Price='+str(a[0]))
    var.set('')          
                
                
                
                
                



lbl=Label(win,text='Enter the area of the house',relief='ridge',fg='black',width=20,bd=5)
lbl.place(x=50,y=10)

var=IntVar()
ent=Entry(win,bd=5,relief='ridge',textvariable=var)
ent.place(x=200,y=10)

btn1=Button(win,text='Submit',bg='green',relief='ridge',bd=5,command=fun)
btn1.place(x=129,y=50)


lbl1=Label(win,text='See Result Here',relief='ridge',fg='black',width=20,bd=5,font=('times new roman',10,'bold'))
lbl1.place(x=50,y=100)







win.mainloop()